### ISSUE TITLE
HALO build number?  

### ISSUE THREAD

**Issue by jimwitkin** [ff36/halo-core#90]
I think it would be a good idea for the build number (version number) to be visible somewhere in the GUI for the Administrator. Maybe on the Manage Halo menu, you could add "About Halo" which shows the version number

**Comment by tarkal** [comment]
I agree. This will a couple of steps;
- Create an API endpoint that returns the core version
- Create an internal semantic versioning system in the GUI
- Create a page in the GUI that displays the versions of the core and GUI to administrators

**Comment by tarkal** [comment]
Fixed in `1.3.0`. The core now reports its version in the response header:

`X-Halo-Version →`

If the system is deployed in debug mode from an IDE the value will return `ide-dev` otherwise it will return the core value.

This has been passed to the GUI for display: https://github.com/ff36/halo-gui/issues/375

**Comment by tarkal** [comment]
fixed in version 1.3.0
